### ISSUE TITLE
Strange error message (TypeError)

### ISSUE THREAD

**Issue by AuraIsMyLife** [iGBAEmu/EclipseIssues#13]
Hey, i wanted to export my state from iGBA to Eclipse and after i copied the Text export state from Eclipse to manually load state in Eclipse and chose iGBA save states this error message turns up:

TypeError: undefined is not an 
                   object (evaluating 
                 JSON.parse(storageJSON).igba.le
                   ngth')

**Comment by 1GamerDev** [comment]
hey, can you send me the state so I can debug it in Twitter DMs?  (@1GamerDev)

**Comment by AuraIsMyLife** [comment]
Yes wait

**Comment by AuraIsMyLife** [comment]
Got it

**Comment by Shugabuga** [comment]
From what @1GamerDev explained to me, it seems like you were importing an iGBA state as an Eclipse state (or vice versa). Make sure you select the origin of the file (what web app generated it).
Closing due to user error.

(He also added auto-detection in Manual importing, so it should work in the next update.)
