### ISSUE TITLE
Cannot press A while holding B, or vice versa.

### ISSUE THREAD

**Issue by NolanHewitt** [iGBAEmu/EclipseIssues#152]
# Description
While it is somewhat possible to press both buttons at almost the same time by sliding a finger across both buttons, in situations where you need to keep B held, while occasionally pressing A (such as in platforming games like the Mario series), it’s not possible to press the A button to jump while also keeping B held to run. I’m not sure how easy this would be to fix, but allowing us to have a layout with the A and B buttons further apart as a work around for these types of games would be very helpful.
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment]
I know it's _slightly_ different, but it's close enough t #151 that it's a duplicate.

You should be able to do the described occasional-tap though. Just keep your finger held and slide between being in between the two buttons and just being over one!

(Our A/B/X/Y buttons are secretly a joystick, so sliding around like this should be valid!)

If it does help, we did tweak the control styles a bit more in v2.2, so it may be more comfortable to do so regardless of what I just said. Cannot confirm, since a lot of controller placement things are based on the size of devices, different people's hands, and personal tastes.
