### ISSUE TITLE
Eclipse Emu Button issue

### ISSUE THREAD

**Issue by Robinhd-Alt** [iGBAEmu/EclipseIssues#70]
I just recently down loaded the Eclipse emu and save it to my browser. Everything is working except the buttons. Only the start buttons work. I’ve seen several similar complaint throughout the past year no response. Did the developer abandon the software?

**Comment by magnetardev** [comment]
No, we haven't abandoned the software. Its just duplicate questions often get disregarded since we already know the issue exists.

It is taking so long because we've been trying to figure out what the actual problem is, and it seems to boil down to how Safari handles events. We hope to fix this in v3, which should come out early this year.

**Comment by Robinhd-Alt** [comment]
Okay, thank you so much for your response.

**Comment by Shugabuga** [comment]
Refer to #45 for further discussion. Closed because duplicate.
